### ISSUE TITLE
Invalid cryptogram

### ISSUE THREAD

**Issue by mrthiti** [sepulo/globalplatform.net#1]
Hello

I use this library but, it error this

http://www.uppicfree.com/view/1c1f5327fb1404813dcce2cff8c6ee9f.jpg

detail:
ENC Key: 404142434445464748494a4b4c4d4e4f
KEK Key: 404142434445464748494a4b4c4d4e4f
MAC Key: 404142434445464748494a4b4c4d4e4f

key version: 0x00
key id: 0x01

**Comment by sepulo** [comment]
Hi, possibly your card uses a key derivation algorithm: emv, visa or visa2. Currently only 'none' derivation is supported. Other algorithms will be added later.
