### ISSUE TITLE
Using smart-cards over TCP/IP

### ISSUE THREAD

**Issue by dancvrcek** [sepulo/globalplatform.net#2]
Hi,

I wonder if you ever thought of plugging smarcars behind a TCP/IP interface for more reliable use.

Thanks
  Dan

**Comment by sepulo** [comment]
Hi,

globalplatform.net designed to be used behind TCP/IP. You may establish secure channel through TCP/IP.

**Comment by sepulo** [comment]
I updated Readme to show how to use it.
